name: food_group_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  path: ^1.9.0
  flutter_svg: ^2.0.9
  flutter_hsvcolor_picker: ^1.5.0
  flutter_rating_bar: ^4.0.1
  gif_view: ^0.4.3
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3
  location: ^5.0.3
  http: ^1.2.0
  package_info_plus: ^6.0.0
  logger: ^2.0.2+1
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: "^0.13.1"
  


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/rating/
    - .env

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "FFCC00"
  image: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: FFCC00

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: assets/images/icon-background.png
  adaptive_icon_foreground: assets/images/icon.png